- name: Build Dynamic Pod Inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get running pods in namespace
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: rhn-support-mtrujill-dev
        field_selectors:
          - status.phase=Running
      register: pod_list

    - name: Add pods to inventory
      ansible.builtin.add_host:
        name: "{{ item.metadata.name }}"
        group: "ocp_pods"
        ansible_connection: kubernetes.core.kubectl
        ansible_host: "{{ item.metadata.name }}"
        # REDIRECT TEMP DIR
        ansible_remote_tmp: /tmp
        # FIX: Using env lookup instead of config query
        ansible_kubectl_server: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
        ansible_kubectl_token: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
        ansible_kubectl_verify_ssl: false
      loop: "{{ pod_list.resources }}"

- name: Test Connections
  hosts: ocp_pods
  gather_facts: false
  tasks:
    - name: Run a direct command
      ansible.builtin.raw: echo "Successfully connected to $(hostname)"
      register: raw_output

    - name: Show Result
      ansible.builtin.debug:
        msg: "{{ raw_output.stdout | trim }}"
